telegram:
  bot-name: ${BOT_NAME}
  bot-token: ${BOT_TOKEN}

server:
  port: 8091

file:
  archive:
    path: music-files/archive
  music:
    path: music-files/music

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

spring:
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  datasource:
    url: jdbc:postgresql://localhost:5432/music_bot
    username: postgres
    password: postgres
    hikari:
      schema: mbt
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    url: jdbc:postgresql://localhost:5432/music_bot
    user: postgres
    password: postgres
    table: flyway_schema_history_tg_music_bot
    locations: classpath:db/migration
    enabled: true
    schemas: mbt

logging:
  level:
    org.springframework.boot: info
    root: info